### ISSUE TITLE
Practica 2

### ISSUE THREAD

**Issue by DuilioAquino10** [SistemasTecTlaxiaco/practica-de-costos-team-pro-2#1]
[Practica 2.pdf](https://github.com/SistemasTecTlaxiaco/practica-de-costos-team-pro-2/files/8134649/Practica.2.pdf)

**Comment by Band-hi** [comment]
18.4%
- Faltan al menos 10 imagenes mas
![image](https://user-images.githubusercontent.com/46431649/155617536-3e0276c8-4aeb-4451-8497-d5cacc9fadfa.png)

**Comment by josealfredo79** [comment]
Bien hecho y revisado
